config/routes.rb
Rails.application.routes.draw do
  root 'calculations#new'

  resources :calculations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mana_source.rb
class ManaSource < ApplicationRecord
  validates :name, presence: true
  validates :white, :blue, :black, :red, :green, :colorless, :etb_tapped, :basic, inclusion: { in: [true, false] }

  scope :alphabetized, -> { order(name: :asc) }

  COLOR_IDENTITIES = {
    white: 'w',
    blue: 'u',
    black: 'b',
    red: 'r',
    green: 'g',
    colorless: 'c'
  }.freeze

  def colors
    [:white, :blue, :black, :red, :green, :colorless].select { |color| send(color) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  COLORS = %w(white blue black red green colorless).freeze

  ManaConstraint = Struct.new(:color, :count, :quantifier, :turn)

  def new
    @non_basic_lands = ManaSource.where(basic: false).alphabetized
    @colors = COLORS
    @amounts = (1..10).to_a
  end

  def create
    @mana_bases = CalculateManaBase.new(mana_constraints, lands_to_consider).call.first(10)
    render :show
  end

  private

  def lands_to_consider
    (params["non_basic_lands"] || []) + colors_desired.flat_map { |color| ManaSource.where(color.to_sym => true, :basic => true) }.pluck('name')
  end

  def mana_constraints
    calculation_params.map do |constraint_params|
      constraint_params_to_mana_constraint(constraint_params)
    end.sort_by { |constraint| COLORS.index(constraint.color) }
  end

  def calculation_params
    params['calculations'].delete_if do |key, _value|
      key == 'constraint_X'
    end
  end

  def colors_desired
    calculation_params.map do |constraint_params|
      constraint_params.second["color"]
    end
  end

  def constraint_params_to_mana_constraint(constraint_params)
    sub_params = constraint_params.second

    ManaConstraint.new(
      sub_params['color'].to_sym,
      sub_params['amount'].to_i,
      sub_params['quantifier'],
      sub_params['turn'].to_i
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
  def mana_icon_for(color)
    content_tag(:i, '', class: "ms ms-cost ms-#{ManaSource::COLOR_IDENTITIES[color]}")
  end
end

app/views/calculations/_constraint.html.erb
<div class='row' id="constraint-<%= id %>">
  <%= form.fields_for("constraint_#{id}") do |fields| %>
    <div class="ui form">
      <div class="fields">

        <div class="field">
          <%= fields.label('i_want', 'I want') %>
        </div>

        <div class="field">
          <%= fields.select('quantifier', options_for_select(["at least", "exactly", "no more than"], "at least"), {}, class: 'ui compact selection dropdown') %>
        </div>

        <div class="field">
          <%= fields.select('amount', options_for_select(amounts, 0), {}, class: 'ui compact selection dropdown') %>
        </div>

        <div class="field">
          <%= fields.select('color', options_for_select(colors, colors.first), {}, class: 'ui compact selection dropdown') %>
        </div>

        <div class="field">
          <%= fields.label('by_turn', 'by turn') %>
        </div>

        <div class="field">
          <%= fields.select('turn', options_for_select((0..10).to_a, 0), {}, class: 'ui compact selection dropdown') %>
        </div>

        <div class="field">
          <%= button_tag(type: 'button', id: "remove-constraint-#{id}", class: 'ui compact icon button') do %>
            <i class="icon remove"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/calculations/_mana_base.html.erb
<tr>
  <% mana_base.each do |key, value| %>
    <% if key == :probability %>
      <td><div class='ui ribbon label'><%= value %>%</div></td>
      <% else %>
      <td> <%= value %> </td>
    <% end %>
  <% end %>
</tr>

app/views/calculations/_non_basic_lands.html.erb
<h3 class='ui header center aligned column'>Choose Nonbasics</h1>

<div class="ui items">
  <div class='ui four column grid'>
    <% lands.each.with_index do |land, index| %>
      <div class='left aligned column'>
        <div class="item" id="nonbasic-land-checkbox-<%= "#{land.multiverse_id}-#{land.colors.join('-')}" %>">
          <%= label_tag "non_basic_lands_#{land.multiverse_id}" do  %>
            <%= check_box_tag "non_basic_lands[]", land.multiverse_id, false,
              {id: "non_basic_lands_#{land.multiverse_id}", class: 'hidden'}%>

            <div class="ui image">
            
              <img src=<%= land.image_url %>>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/calculations/new.html.erb
<div class='ui main container' id='calculation-container'>
    <h1 class='ui header center aligned column'>Manabase Construction</h1>

  <%= form_for :calculations, url: calculations_path, class: 'ui large form' do |f| %>
    <div class="ui two column grid">
      <div class="center aligned column">
        <div id='constraints' class='ui seven column doubling stackable grid container'>
          <%= render partial: 'constraint', locals: { color: @colors.first, colors: @colors, amounts: @amounts, form: f, id: 0 } %>
        </div>

        <div class='one column row'>
          <%= button_tag(type: 'button', id: 'add-constraint', class: 'ui labeled icon button') do %>
            <i class="plus icon"></i>
            Add constraint
          <% end %>
        </div>

        <div class='one column row'>
          <%= f.submit 'Calculate', id: 'submit-calculation', class: 'ui large teal submit button' %>
        </div>
      </div>

      <div class="center aligned column">
        <h3 class='ui header center aligned column'>Choose Nonbasics</h1>

        <div class='ui three column grid'>
          <% @non_basic_lands.each.with_index do |land, index| %>
            <div class='left aligned column'>
              <div class='ui checkbox' id="nonbasic-land-checkbox-<%= "#{land.name.downcase.delete(' ')}-#{land.colors.join('-')}" %>">
                <%= check_box_tag "non_basic_lands[]", land.name %>
                <%= label_tag "non_basic_lands_#{land.name}" do  %>
                  <%= land.name %>
                  <% land.colors.each do |color| %>
                    <%= mana_icon_for(color) %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>


    <div id='constraint-template' style='display:none'>
      <%= render partial: 'constraint', locals: { color: @colors.first, colors: @colors, amounts: @amounts, form: f, id: 'X' } %>
    </div>
  <% end %>
</div>

app/views/calculations/show.html.erb
<div class='ui main text container' id='calculation-form'>
  <h1 class='ui header'>Manabases calculated</h1>

  <% if @mana_bases.empty? %>
    <p>Sorry, we couldn't find any mana bases that met your constraints.</p>
  <% else %>
    <p>The following mana configurations are the most optimal for your requirements:</p>

    <table class="ui celled table">
      <thead>
        <tr>
        <% @mana_bases.flat_map(&:keys).uniq.each do |column_title| %>
          <th><%= h column_title %></th>
        <% end %>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'mana_base', collection: @mana_bases %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/layouts/_top_menu.html.erb
<div class='ui fixed inverted menu'>
  <div class='ui container'>
    <%= link_to 'Manulator', root_path, class: 'header item' %>
    <!-- <a href='#' class='header item'> -->
      <!-- <img class='logo' src='assets/images/logo.png'> -->
    <!-- Manulator
         </a> -->
    <!-- <div class='ui simple dropdown item'>
         Dropdown <i class='dropdown icon'></i>
         <div class='menu'>
         <a class='item' href='#'>Link Item</a>
         <a class='item' href='#'>Link Item</a>
         <div class='divider'></div>
         <div class='header'>Header Item</div>
         <div class='item'>
         <i class='dropdown icon'></i>
         Sub Menu
         <div class='menu'>
         <a class='item' href='#'>Link Item</a>
         <a class='item' href='#'>Link Item</a>
         </div>
         </div>
         <a class='item' href='#'>Link Item</a>
         </div>
         </div> -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manulator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/top_menu' %>
    <%= yield %>
  </body>
</html>